---
- name: Install haproxy
  ansible.builtin.apt:
    name:
      - "haproxy"
    state: present

- name: Install haproxy configuration for K8s API servers
  ansible.builtin.template:
    src: etc/haproxy/k8s_api_endpoint.cfg.j2
    dest: /etc/haproxy/k8s_api_endpoint.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload haproxy

- name: Ensure haproxy systemd drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/system/haproxy.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install haproxy systemd drop-in
  ansible.builtin.template:
    src: etc/systemd/system/haproxy.service.d/override.conf.j2
    dest: /etc/systemd/system/haproxy.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart haproxy
