---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

# Use "systemd-timesyncd" for time services. It's available by default.
harden_linux_ntp: "systemd-timesyncd"

# Password for user "root" and "vagrant" is "vagrant" in both cases. As
# "vagrant" user is available in every Vagrant Ubuntu Box just use it.
harden_linux_root_password: "$6$rounds=656000$mysecretsalt$fpyQ9hMON6iKKuM0Rz10WZKNJR4OkQTVfBmd4SPrJPsU9XmgQGRtogcUnFB5FLRIitswuQFr6Tr8Mos9l7Ojm0"
harden_linux_deploy_user: "vagrant"
harden_linux_deploy_user_password: "$6$rounds=656000$mysecretsalt$fpyQ9hMON6iKKuM0Rz10WZKNJR4OkQTVfBmd4SPrJPsU9XmgQGRtogcUnFB5FLRIitswuQFr6Tr8Mos9l7Ojm0"
harden_linux_deploy_user_home: "/home/vagrant"
harden_linux_deploy_user_uid: "1000"
harden_linux_deploy_user_shell: "/bin/bash"

# Enable IP forwarding for IPv4 and IPv6
harden_linux_sysctl_settings_user:
  "net.ipv4.ip_forward": 1
  "net.ipv6.conf.default.forwarding": 1
  "net.ipv6.conf.all.forwarding": 1

# Let SSHd listen on port 22, allow password authentication and allow "root"
# login. The last two settings are not recommended for production use but for
# this test deployment it's okay as it makes debugging easier and faster.
harden_linux_sshd_settings_user:
  "^Port ": "Port 22"
  "^PasswordAuthentication": "PasswordAuthentication yes"
  "^PermitRootLogin": "PermitRootLogin yes"

# Enable logging for UFW.
harden_linux_ufw_logging: 'on'

# Set the default forward policy to "ACCEPT".
harden_linux_ufw_defaults_user:
  "^DEFAULT_FORWARD_POLICY": 'DEFAULT_FORWARD_POLICY="ACCEPT"'

# Don't block SSH logins from the following networks even login attempts fail
# for a few times.
harden_linux_sshguard_whitelist:
  - "127.0.0.0/8"
  - "::1/128"
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"

# Directory where the etcd certificates are stored on the Ansible controller
# host.
etcd_ca_conf_directory: "/tmp/k8s"
# Directory where the etcd certificates are stored on the etcd hosts.
etcd_conf_dir: "/etc/etcd"
# Interface where the etcd service is listening on.
etcd_interface: "{{ k8s_interface }}"
# A few additional settings for etcd.
etcd_settings_user:
  "heartbeat-interval": "250"
  "election-timeout": "2500"
# Host names and IP addresses in the etcd certificates.
etcd_cert_hosts:
  - localhost
  - 127.0.0.1
  - 10.32.0.1
  - 192.168.10.5
  - 192.168.10.10
  - 192.168.10.20
  - 192.168.10.30
  - 192.168.10.100
  - 192.168.10.110
  - 192.168.10.120
  - 192.168.10.130
  - 10.10.10.5
  - 10.10.10.10
  - 10.10.10.20
  - 10.10.10.30
  - 10.10.10.100
  - 10.10.10.110
  - 10.10.10.120
  - 10.10.10.130
  - test-controller1
  - test-controller2
  - test-controller3
  - test-worker1
  - test-worker2
  - test-worker3

# Directory where the Kubernetes certificates are stored on the Ansible
# controller host.
k8s_ca_conf_directory: "/tmp/k8s"
# Permissions for the Kubernetes CA directory.
k8s_ca_conf_directory_perm: "0700"
# Permissions for the Kubernetes CA files.
k8s_ca_file_perm: "0600"
# Owner of the Kubernetes CA files.
k8s_ca_certificate_owner: "{{ k8s_config_owner }}"
# Group of the Kubernetes CA files.
k8s_ca_certificate_group: "{{ k8s_config_group }}"

# Interface where the Kubernetes control plane services are listening on.
k8s_interface: "wg0"
# Delegate tasks like creating the Kubernetes CA certificates to the following
# host. This host also communicates with the "kube-apiserver" if required
# for certain tasks.
k8s_controller_delegate_to: "test-assets"

# The name of the Kubernetes cluster.
k8s_config_cluster_name: "k8s"
# Stores the "kubeconfig" of the "admin" user.
k8s_config_directory: "/tmp/k8s"
# Permissions for the Kubernetes config directory.
k8s_config_directory_perm: "0700"
# Permissions for the Kubernetes config files.
k8s_config_file_perm: "0600"
# Owner of the Kubernetes config files.
k8s_config_owner: "vagrant"
# Group of the Kubernetes config files.
k8s_config_group: "vagrant"

# Key used for encrypting secrets (encryption at-rest) by the
# "kube-apiserver".
k8s_encryption_config_key: "Y29uZmlndXJhdGlvbjIyCg=="

# Additional settings for the "kube-apiserver".
k8s_apiserver_settings_user:
  "enable-aggregator-routing": "true"

k8s_worker_kubelet_conf_dir: "/var/lib/kubelet"

k8s_worker_kubelet_settings:
  "config": "{{ k8s_worker_kubelet_conf_dir }}/kubelet-config.yaml"
  "node-ip": "{{ hostvars[inventory_hostname]['ansible_' + k8s_interface].ipv4.address }}"
  "kubeconfig": "{{ k8s_worker_kubelet_conf_dir }}/kubeconfig"
  "seccomp-default": ""

# Directory for the "runc" binaries
runc_bin_directory: "/usr/local/sbin"

# Directory to store the "containerd" archive after download
containerd_tmp_directory: "/tmp"

# Don't use "etcd" for Cilium
cilium_etcd_enabled: "false"
# Delegate Cilium tasks that needs to communicate with the Kubernetes API
# server to the following host.
cilium_delegate_to: "test-assets"
# Show debug output for Cilium Helm commands.
cilium_helm_show_commands: true

# Delegate tasks to create CoreDNS K8s resources to this host.
coredns_delegate_to: "test-assets"

# Common name for "etcd" certificate authority certificates.
ca_etcd_csr_cn: "etcd"

# Common name for "kube-apiserver" certificate authority certificate.
ca_k8s_apiserver_csr_cn: "kubernetes"

# Common names for "etcd" server, peer and client certificates.
etcd_server_csr_cn: "etcd"
etcd_peer_csr_cn: "etcd"
etcd_client_csr_cn_prefix: "etcd"

# Common names for kube-apiserver, admin and kube-controller-manager certificates.
k8s_apiserver_csr_cn: "kubernetes"
k8s_admin_csr_cn: "admin"
k8s_controller_manager_sa_csr_cn: "service-accounts"
