---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart kube-proxy
  ansible.builtin.service:
    name: kube-proxy
    state: restarted

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
